name: in_app_purchases_paywall_ui
description: >
  A collection of in app purchase PayWalls as a UI library.
  More UIs will follow. Subscriptions are supported.
version: 0.1.1
homepage: https://github.com/LinkFive/flutter-in_app_purchases_paywall
repository: https://github.com/LinkFive/flutter-in_app_purchases_paywall

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.3.2
  in_app_purchases_interface: ^0.0.2
    #path: ../in_app_purchases_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
