name: in_app_purchases_intl
description: Intl Package for common translations in your In App Purchase App
version: 0.0.2
homepage: https://github.com/LinkFive/flutter-in_app_purchases_paywall
repository: https://github.com/LinkFive/flutter-in_app_purchases_paywall

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  generate: true